name: Network CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        dotnet-version: 9.x
        source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
    - name: Get version info
      uses: andrewmclachlan/actions/get-version-number-from-project@v4
      id: get-version-number
      with:
        project: src/UniFi.Net.Network/UniFi.Net.Network.csproj
    - name: Package
      run: |
        dotnet pack src/UniFi.Net.Network -o ${{ github.workspace }}/publish --configuration Release --p:Version=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.0.0 \
        --p:FileVersion=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.0.${{ github.run_number }} \
        --p:PackageVersion=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}.0-ci.${{ github.run_number }}
    - name: Publish Packages
      if: ((github.event_name == 'workflow_dispatch' || github.event_name == 'push') && github.ref == 'refs/heads/main')
      run: dotnet nuget push ${{ github.workspace }}/publish/**/*.nupkg --api-key ${{secrets.GITHUB_TOKEN}} --skip-duplicate
