name: Network CI

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        dotnet-version: 9.x
        source-url: https://nuget.pkg.github.com/AndrewMcLachlan/index.json
    - uses: andrewmclachlan/actions/get-version-number-from-project@feature/get-version-from-tag
      id: get-version-number
    - name: Package
      run: |
        dotnet pack src/UniFi.Net.Network -o ${{ github.workspace }}/publish --configuration Release --p:Version=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }} \
        --p:FileVersion=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}-ci.${{ github.run_number }} \
        --p:PackageVersion=${{ steps.get-version-number.outputs.major }}.${{ steps.get-version-number.outputs.minor }}-ci.${{ github.run_number }}
    - name: Publish Packages
      if: (github.event_name != 'pull_request' && github.event_name != 'pull_request_target' && github.ref == 'refs/heads/main')
      run: dotnet nuget push ${{ github.workspace }}/publish/**/*.nupkg
